extends:
  - eslint:all
  - google
  - plugin:react/all

parser: babel-eslint

env:
  browser: true
  es6: true
  node: true

globals:
  PROJECT_NAME: true
  VERSION: true

rules:
  arrow-parens: [error, as-needed]
  brace-style: [error, 1tbs, allowSingleLine: true]
  block-spacing: [error, always]
  capitalized-comments: warn
  class-methods-use-this: off
  dot-location: [error, property]
  id-length: off
  indent:
    - error
    - 2
    - SwitchCase: 1
      FunctionDeclaration:
        parameters: 2
      FunctionExpression:
        parameters: 2
  func-names: [error, as-needed]
  func-style: off
  function-paren-newline: off
  implicit-arrow-linebreak: off
  multiline-ternary: [error, always-multiline]
  newline-per-chained-call:
    - error
    - ignoreChainWithDepth: 2
  no-extra-parens:
    - error
    - all
    - nestedBinaryExpressions: false
  no-ternary: off
  operator-linebreak: [error, before]
  semi-style: off
  sort-imports: off
  sort-keys: off
  max-len: off
  max-lines: warn
  multiline-comment-style: warn
  new-cap:
    - error
    - capIsNewExceptions:
      - List
      - Map
      - Range
      - Record
  no-console: warn
  no-else-return: off
  no-magic-numbers: off
  object-curly-newline:
    - error
    - consistent: true
      multiline: true
  object-curly-spacing: [error, always]
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  padded-blocks: off
  react/destructuring-assignment: off
  react/forbid-prop-types:
    - warn
    - checkChildContextTypes: true
      checkContextTypes: true
  react/jsx-boolean-value: [error, alwaysaligned]
  react/jsx-closing-bracket-location: [error, line-aligned]
  react/jsx-closing-tag-location: off
  react/jsx-curly-spacing: [error, always]
  react/jsx-handler-names: off
  react/jsx-indent-props: [error, 2]
  react/jsx-indent: [error, 2]
  react/jsx-max-depth: off
  react/jsx-no-bind: off
  react/jsx-no-literals: off
  react/jsx-sort-props:
    - error
    - callbacksLast: false
      ignoreCase: true
      reservedFirst: true
  react/jsx-tag-spacing:
    - error
    - afterOpening: never
      beforeClosing: never
      beforeSelfClosing: never
      closingSlash: never
  react/jsx-wrap-multilines: off
  react/no-deprecated: warn
  react/no-did-mount-set-state: [error, disallow-in-func]
  react/no-did-update-set-state: [error, disallow-in-func]
  react/no-multi-comp: off
  react/no-set-state: off
  react/no-will-update-set-state: [error, disallow-in-func]
  react/require-default-props: off
  react/require-optimization: warn
  react/sort-comp:
    - error
    - order:
      - static-methods
      - lifecycle
      - everything-else
      - /^on[A-Z].*$/
      - /^render.+$/
      - render
  react/sort-prop-types:
    - error
    - callbacksLast: true
      ignoreCase: true
      requiredFirst: true
      sortShapeProp: true
  react/static-property-placement: off
  require-jsdoc: off
